language: haskell
ghc:
  - "7.8"
  - "7.10"
  - "8.0"
  - "8.2"
  - "8.4"
  - "8.6"
os:
  - linux
before_script:
  - cabal sdist
  - mkdir travisbuild
  - mv dist/HaTeX*.tar.gz travisbuild/HaTeX.tar.gz
  - cd travisbuild
  - tar xzvf HaTeX.tar.gz
  - cd HaTeX*
script:
  - cabal configure --enable-tests --ghc-option=-Werror
  - cabal build
  - cabal test
sudo: false
