
-- |
-- 
-- /For contributors: This module was automatically generated by HaTeX-meta./
-- /So, please, don't make any change here directly, because/
-- /this is intended to be generated automatically from/
-- "Text.LaTeX.Packages.AMSFonts" /module via HaTeX-meta,/
-- /and therefore, changes must to be done in these places./

module Text.LaTeX.Packages.AMSFonts.Monad
 ( -- * AMSFonts package
   amsfonts
   -- * Fonts
 , mathbb
   ) where

import Text.LaTeX.Base.Writer
import Control.Monad (liftM)
import Text.LaTeX.Base.Render
import Text.LaTeX.Base.Types
import qualified Text.LaTeX.Packages.AMSFonts as App
import Text.LaTeX.Packages.AMSFonts()

{-|
AMSFonts package.
 Example:

>  usepackage [] amsfonts

-}
amsfonts :: ClassName
amsfonts = App.amsfonts

{-|
This font is useful for representing sets like
   R (real numbers) or Z (integers). For instance:

>  "The set of real numbers are represented by " <> mathbb "R" <> "."

Or in monadic form:

>  "The set of real numbers are represented by " >> mathbb "R" >> "."

/Note the use of overloaded strings./
-}
mathbb ::   (Monad m) => LaTeXT_ m -> LaTeXT_ m
mathbb a1
  = do a1 <- extractLaTeX_ a1
       textell ( App.mathbb a1)


