{-# LANGUAGE OverloadedStrings #-}

{-|
This module allows you to use the LaTeX graphicx library in order to
   insert graphics in a document.
-}-- 
-- /For contributors: This module was automatically generated by HaTeX-meta./
-- /So, please, don't make any change here directly, because/
-- /this is intended to be generated automatically from/
-- "Text.LaTeX.Packages.Graphicx" /module via HaTeX-meta,/
-- /and therefore, changes must to be done in these places./

module Text.LaTeX.Packages.Graphicx.Monad
 ( -- * Graphicx package
   graphicx
   -- * Package options
 , dvips
 , dvipdfm
 , pdftex
   -- * Including graphics
 , IGOption (..)
 , includegraphics
   ) where

import Text.LaTeX.Base.Writer
import Text.LaTeX.Base.Render
import Text.LaTeX.Base.Types
import qualified Text.LaTeX.Packages.Graphicx as App
import Text.LaTeX.Packages.Graphicx(IGOption)

{-|
The 'graphicx' package.

>  usepackage [] graphicx

-}
graphicx :: PackageName
graphicx = App.graphicx


dvips ::   (Monad m) => LaTeXT_ m
dvips = do textell ( App.dvips)


dvipdfm ::   (Monad m) => LaTeXT_ m
dvipdfm = do textell ( App.dvipdfm)


pdftex ::   (Monad m) => LaTeXT_ m
pdftex = do textell ( App.pdftex)

-- | Include an image in the document.

includegraphics ::   (Monad m) => [IGOption] -> FilePath -> LaTeXT_ m
includegraphics a1 a2 = do textell ( App.includegraphics a1 a2)


